changelog:
  exclude:
    labels:
      - skip-changelog
      - chore
      - dependencies
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Maintenance
      labels:
        - maintenance
        - refactor
